### ISSUE TITLE
win搜索歌曲报错

### ISSUE THREAD

**Issue by brucmao** [zonemeen/musicn#13]
win10  node版本 ：v16.15.0
使用如下命令安装的musicn
```
scoop install nodejs-lts pnpm
pnpm add -g musicn
```

安装后使用 报错
` msc 稻香`
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\brucm\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\got@11.8.3\node_modules\got\dist\source\core\index.js:962:111)    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (C:\Users\brucm\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\@szmarczak+http-timer@4.0.6\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1652756875734,
    socket: 1652756875735,
    lookup: 1652756875737,
    connect: 1652756875739,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1652756880750,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: 2,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5016
    }
  }
}

**Comment by zonemeen** [comment]
> 

你好 你换yarn 安装试试

**Comment by brucmao** [comment]
yarn global add musicn.js
yarn global v1.22.19
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/musicn.js: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/share/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by brucmao** [comment]
我在wsl试了下也无法使用
yarn global add musicn
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "musicn@1.2.6" with binaries:
      - musicn
      - msc
Done in 4.24s.



msc 稻香
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/root/.local/share/pnpm/global/5/.pnpm/got@11.8.3/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/root/.local/share/pnpm/global/5/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1652770088478,
    socket: 1652770088479,
    lookup: 1652770088481,
    connect: 1652770088482,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1652770093490,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: 1,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5012
    }
  }
}
