### ISSUE TITLE
终于用上了，但是有时候搜索某些歌曲会报错

### ISSUE THREAD

**Issue by brucmao** [zonemeen/musicn#17]
<img width="1047" alt="Snipaste_2022-05-18_00-06-48" src="https://user-images.githubusercontent.com/6119652/168857844-033790df-d235-4bc5-8b6b-40981430851f.png">

``` msc palladio
file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/names.js:4
  const { pathname } = new URL(option.androidUrl || option.url)
                                      ^

TypeError: Cannot read properties of undefined (reading 'androidUrl')
    at names (file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/names.js:4:39)
    at file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/choose.js:10:43
    at Array.map (<anonymous>)
    at choose (file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/choose.js:10:22)
    at musicn (file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/index.js:8:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/bin/musicn.js:8:3`
```

**Comment by zonemeen** [comment]
> <img alt="Snipaste_2022-05-18_00-06-48" width="1047" src="https://user-images.githubusercontent.com/6119652/168857844-033790df-d235-4bc5-8b6b-40981430851f.png">
> 
> ```
> file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/names.js:4
>   const { pathname } = new URL(option.androidUrl || option.url)
>                                       ^
> 
> TypeError: Cannot read properties of undefined (reading 'androidUrl')
>     at names (file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/names.js:4:39)
>     at file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/choose.js:10:43
>     at Array.map (<anonymous>)
>     at choose (file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/choose.js:10:22)
>     at musicn (file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/lib/index.js:8:26)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async file:///C:/Users/brucm/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/musicn@1.2.6/node_modules/musicn/bin/musicn.js:8:3`
> ```

你好 这个问题fix了 可以下载最新版本
