### ISSUE TITLE
SyntaxError: Unexpected token  

### ISSUE THREAD

**Issue by wp771910012** [zonemeen/musicn#2]
➜  Downloads msc 稻香
/usr/local/lib/node_modules/musicn/lib/search.js:12
  const songs = JSON.parse(body).songResultData?.result
                                                ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/musicn/lib/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by zonemeen** [comment]
> ➜ Downloads msc 稻香 /usr/local/lib/node_modules/musicn/lib/search.js:12 const songs = JSON.parse(body).songResultData?.result ^
> 
> SyntaxError: Unexpected token . at Module._compile (internal/modules/cjs/loader.js:723:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/usr/local/lib/node_modules/musicn/lib/index.js:3:16) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

你node版本应该太低了 要14以上

**Comment by yyman001** [comment]
@zonemeen 建议在文档写上node版本要求
