### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by faimin** [zonemeen/musicn#39]
```javascript
❯ msc --version

/Users/momo/.nvm/versions/node/v11.12.0/lib/node_modules/musicn/bin/cli.js:3
import cli from '../dist/index.js'
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

是我本地哪个环境配置的有问题吗？

**Comment by zonemeen** [comment]
> ```js
> ❯ msc --version
> 
> /Users/momo/.nvm/versions/node/v11.12.0/lib/node_modules/musicn/bin/cli.js:3
> import cli from '../dist/index.js'
>        ^^^
> 
> SyntaxError: Unexpected identifier
>     at Module._compile (internal/modules/cjs/loader.js:743:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
>     at Module.load (internal/modules/cjs/loader.js:666:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:598:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
>     at internal/main/run_main_module.js:21:11
> ```
> 
> 是我本地哪个环境配置的有问题吗？

你好，你node的版本太低了，需要升级到16以上的版本才可使用

**Comment by faimin** [comment]
谢谢
