### ISSUE TITLE
msc 周杰伦 报错

### ISSUE THREAD

**Issue by Begin-With-Start** [zonemeen/musicn#45]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /usr/local/lib/node_modules/musicn/dist/index.js

node -v
v14.17.6

**Comment by fedono** [comment]
同上，切换 node 版本 v12.22.1 / v14.19.3 均出现这个问题，切换到 v16.13.0 可以用了 

@Begin-With-Start

**Comment by zonemeen** [comment]
> internal/process/esm_loader.js:74 internalBinding('errors').triggerUncaughtException( ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /usr/local/lib/node_modules/musicn/dist/index.js at packageResolve (internal/modules/esm/resolve.js:664:9) at moduleResolve (internal/modules/esm/resolve.js:705:18) at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11) at Loader.resolve (internal/modules/esm/loader.js:89:40) at Loader.getModuleJob (internal/modules/esm/loader.js:242:28) at ModuleWrap. (internal/modules/esm/module_job.js:73:40) at link (internal/modules/esm/module_job.js:72:36) { code: 'ERR_MODULE_NOT_FOUND' }
> 
> node -v v14.17.6

你好，node版本得16以上才能用
